### ISSUE TITLE
#pragma preserve_names logic

### ISSUE THREAD

**Issue by Levitanus** [nojanath/SublimeKSP#77] opened 2017-10-28 19:34 UTC
Well, it took time to understand how to make them work in the particular case:
I'm not sure, that convert dots to underscores works for this pragma
and i definitely sure it doesn't count the namespace, placed by the script with import function
but pragmas still works if place them into separate module, adding namespace and double__underscores instead of every.dot, including one, that is used by namespace functional.

**Comment by mkruselj** [comment] 2017-11-10 10:52
Hmmm, variables with dots work with preserve_names pragma over here (not using namespaces though).

**Comment by neblix** [comment] 2017-11-12 02:44
Please provide example code to show what the issue is.

I have done a simple test here:

```{ #pragma preserve_names bar }

on init
	declare bar
end on```

This is a file "test2.ksp". It contains a variable which will be imported to another script:

```import 'test2.ksp' as foo

on init
	message(foo.bar)
end on
```

When this compiles, the foo.bar variable survives name compaction as intended:

```{ Compiled on Sat Nov 11 21:43:12 2017 }
on init
  declare $foo__bar
end on

on init
  message($foo__bar)
end on```

**Comment by pryzmusic** [comment] 2020-04-13 23:58
Closing this issue since no instructions were provided to reproduce the problem.

**Closed by pryzmusic** 2020-04-13 23:58 UTC
