### ISSUE TITLE
Allow variable declarations in any CB

### ISSUE THREAD

**Issue by JackWilliams-FractureSounds** [nojanath/SublimeKSP#319] opened 2023-03-05 01:27 UTC
Move variables to init CB. 
If local, assign unique ID for variables in different callbacks

```
on listener
    declare local i := 5
end on

on ui_control(mySwitch)
   declare i := 5
end on
```
compiles to...
```
on init
   declare $_on_listener__i := 5
   declare $i := 5
end on

on listener
    $_on_listener__i := 5
end on

on ui_control(mySwitch)
   $ i := 5
 end on

```

**Comment by mkruselj** [comment] 2023-03-06 21:10
Duplicate of  #56 basically :)

**Comment by JackWilliams-FractureSounds** [comment] 2023-03-06 21:11
Oop let's close this then haha

**Closed** 2023-03-06 21:12 UTC
