### ISSUE TITLE
SublimeKSP Autocomplete Issue: NIKontakt Variables vs. User Variables

### ISSUE THREAD

**Issue by lswissdev** [nojanath/SublimeKSP#425] opened 2023-12-25 18:12 UTC
I'm facing an issue in NI Kontakt Script KSP where the autocomplete feature doesn't display both native and user variables simultaneously. In one version, only native variables are visible in the autocomplete list, while in another, only user variables appear in the code. I'd like to learn how to configure SublimeKSP to show both variable types in the autocomplete list during script development.

**Comment by mkruselj** [comment] 2024-01-09 09:54
Hmmm, I'm not sure how to even reproduce this...

**Comment by mkruselj** [comment] 2024-07-11 16:04
Closing due to lack of reproducible steps. If anyone finds a way to reproduce this, please reopen the issue.

**Closed by mkruselj** 2024-07-11 16:04 UTC
